// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA8lq7hLChFoc09axjtIuoF1p8Is6bD-A',
    appId: '1:25194491712:web:3a338bf973ba4b0bd8d4a5',
    messagingSenderId: '25194491712',
    projectId: 'mytestf-6c08c',
    authDomain: 'mytestf-6c08c.firebaseapp.com',
    storageBucket: 'mytestf-6c08c.appspot.com',
    measurementId: 'G-6EVF9WJ1K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvHGIPPqgHDWvB3JiiHg9FtH2m5nZMR2k',
    appId: '1:25194491712:android:8293196ad597c38bd8d4a5',
    messagingSenderId: '25194491712',
    projectId: 'mytestf-6c08c',
    storageBucket: 'mytestf-6c08c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMNctoTQHfZy3mBdzCS-lpGJ3zDXr30es',
    appId: '1:25194491712:ios:8e257817330eda30d8d4a5',
    messagingSenderId: '25194491712',
    projectId: 'mytestf-6c08c',
    storageBucket: 'mytestf-6c08c.appspot.com',
    iosBundleId: 'com.example.swf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMNctoTQHfZy3mBdzCS-lpGJ3zDXr30es',
    appId: '1:25194491712:ios:8e257817330eda30d8d4a5',
    messagingSenderId: '25194491712',
    projectId: 'mytestf-6c08c',
    storageBucket: 'mytestf-6c08c.appspot.com',
    iosBundleId: 'com.example.swf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA8lq7hLChFoc09axjtIuoF1p8Is6bD-A',
    appId: '1:25194491712:web:e38329dd0fd46fded8d4a5',
    messagingSenderId: '25194491712',
    projectId: 'mytestf-6c08c',
    authDomain: 'mytestf-6c08c.firebaseapp.com',
    storageBucket: 'mytestf-6c08c.appspot.com',
    measurementId: 'G-CZSLQ4XT05',
  );
}
